# Generated by Django 3.2.9 on 2021-12-04 19:49

from django.db import migrations, models
from FashionGAN.models import filepath

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0, null=True)),
                ('image', models.ImageField(upload_to=filepath)),
                ('discription', models.CharField(max_length=50)),
            ],
        ),
    ]
