# Generated by Django 3.2.9 on 2021-12-05 07:37

import FashionGAN.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FashionGAN', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discription',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to=FashionGAN.models.filepath),
        ),
    ]
